name: "Test"
on:
  pull_request:
    paths-ignore:
    - '**.md'
    - 'screenshots/**'
    - 'windows/**'
  push:
    paths-ignore:
    - '**.md'
    - 'screenshots/**'
    - 'windows/**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Enable debug'
        type: boolean
        required: false
        default: false
jobs:
  transcribe:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: nixbuild/nix-quick-install-action@v21
      with:
        nix_conf: |
          experimental-features = nix-command flakes
          keep-derivations = true
          keep-outputs = true
    - uses: cachix/cachix-action@v12
      with:
        name: azuwis
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Pre cache
      run: |
        mv -v /nix/store /nix/store.bak
        mv -v /nix/var/nix/db/db.sqlite /nix/var/nix/db/db.sqlite.bak
    - uses: actions/cache@v3
      with:
        key: pianotrans3-${{ matrix.os }}-${{ hashFiles('flake.*', 'nix/**') }}
        restore-keys: |
          pianotrans3-${{ matrix.os }}-
        path: |
          /nix/store
          /nix/var/nix/db/db.sqlite
    - name: Post cache
      run: |
        if ! nix --version
        then
          if [ -e /nix/store ]
          then
            # cache hit, but nix changed
            mv -v /nix/store /nix/var/nix/db/db.sqlite /tmp
          fi
          mv -v /nix/store.bak /nix/store
          mv -v /nix/var/nix/db/db.sqlite.bak /nix/var/nix/db/db.sqlite
        fi
    - uses: lhotari/action-upterm@v1
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      with:
        limit-access-to-actor: true
    - name: tess torchBin
      run: |
        nix shell -f pianotrans-tests.nix torchBin --command pianotrans --cli test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus | grep 'Transcribe time:'
    - name: test mklDnnOn, no Accelerate.framework
      run: |
        nix shell github:nixos/nixpkgs/144ede9ee61ecfcc2d6b322398647e6908aa0db4#pianotrans --command pianotrans --cli test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus | grep 'Transcribe time:'
    - name: test mklDnnOff, has Accelerate.framework
      run: |
        nix shell -f pianotrans-tests.nix mklDnnOff --command pianotrans --cli test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus | grep 'Transcribe time:'
    - name: test mklDnnOn, has Accelerate.framework
      run: |
        nix shell -f pianotrans-tests.nix mklDnnOn --command pianotrans --cli test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus test/cut_liszt.opus | grep 'Transcribe time:'
    - name: Nix GC
      run: |
        # delete old stuff not relevant to this build
        nix-collect-garbage -d
